# Generated by Django 5.1.1 on 2024-10-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_notification_is_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='static/image/logo.png', upload_to='new_library'),
        ),
    ]
